//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRemoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class matches
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public matches()
        {
            this.goals = new HashSet<goals>();
        }
    
        public int id { get; set; }
        public Nullable<int> idCompetition { get; set; }
        public Nullable<int> idHome { get; set; }
        public Nullable<int> idAway { get; set; }
        public Nullable<int> goalsHome { get; set; }
        public Nullable<int> goalsAway { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<bool> isRegular { get; set; }
        public Nullable<bool> isFullGoal { get; set; }
        public Nullable<bool> isExtraTime { get; set; }
        public string round { get; set; }
        public string link { get; set; }
        public string stage { get; set; }
    
        public virtual competitions competitions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<goals> goals { get; set; }
        public virtual teams teams { get; set; }
        public virtual teams teams1 { get; set; }
    }
}
