//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRemoto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class sportEntities : DbContext
    {
        public sportEntities()
            : base("name=sportEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<competitions> competitions { get; set; }
        public virtual DbSet<goals> goals { get; set; }
        public virtual DbSet<leagues> leagues { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<matches> matches { get; set; }
        public virtual DbSet<nations> nations { get; set; }
        public virtual DbSet<nextmatches> nextmatches { get; set; }
        public virtual DbSet<players> players { get; set; }
        public virtual DbSet<Santi> Santi { get; set; }
        public virtual DbSet<seasons> seasons { get; set; }
        public virtual DbSet<standings> standings { get; set; }
        public virtual DbSet<teams> teams { get; set; }
    }
}
