//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRemoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nextmatches
    {
        public int id { get; set; }
        public Nullable<int> idNation { get; set; }
        public Nullable<int> idCompetition { get; set; }
        public Nullable<int> idHome { get; set; }
        public Nullable<int> idAway { get; set; }
        public string Home { get; set; }
        public string Away { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> IsDone { get; set; }
    }
}
