//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRemoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Santi
    {
        public int Id { get; set; }
        public string Nome { get; set; }
        public string Titolo { get; set; }
        public string Qualifica { get; set; }
        public string Data { get; set; }
        public string Secolo { get; set; }
        public string Storia { get; set; }
        public string Emblema { get; set; }
        public string Etimologia { get; set; }
        public string Martirologio { get; set; }
        public Nullable<int> Mese { get; set; }
        public Nullable<int> Giorno { get; set; }
    }
}
