//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseRemoto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class standings
    {
        public int id { get; set; }
        public Nullable<int> competition_id { get; set; }
        public Nullable<int> position { get; set; }
        public string team { get; set; }
        public Nullable<int> numberOfMatches { get; set; }
        public Nullable<int> wins { get; set; }
        public Nullable<int> deuces { get; set; }
        public Nullable<int> losses { get; set; }
        public Nullable<int> goals { get; set; }
        public Nullable<int> takenGoals { get; set; }
        public Nullable<int> points { get; set; }
        public string notes { get; set; }
    
        public virtual competitions competitions { get; set; }
    }
}
